import { Suspense, lazy, useCallback, useEffect, useState, type CSSProperties } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, BookOpen, ChevronDown, ChevronRight, RefreshCw } from 'lucide-react';
import { apiService } from '../services/api';
import type { Expert, ExpertRunResult, ExpertTopic, ExpertBriefingHistoryEntry } from '../services/api';

// react-markdown + rehype pulls a ~100 KB gz chunk. A track with no expert bound,
// or no briefing yet, must not pay for it, so it loads only when there is markdown.
const MarkdownRenderer = lazy(() => import('./ui/MarkdownRenderer'));

/**
 * The stored topic briefing for the expert bound to this folder, rendered inside
 * the folder itself instead of only on /experts.
 *
 * Read-only: it fetches the LATEST STORED briefing. It never triggers generation,
 * so opening a track costs zero model tokens.
 */

function asArray<T>(value: unknown): T[] {
  return Array.isArray(value) ? (value as T[]) : [];
}

/**
 * MarkdownRenderer paints with the System A theme tokens (var(--text-normal) & co).
 * This page is hard-coded light (bg-gray-50 / white cards) regardless of the theme
 * toggle, so we pin the light values inside the markdown subtree — otherwise the
 * dark theme renders near-white text on a white card.
 */
const LIGHT_MARKDOWN_VARS = {
  '--text-normal': '#1F2937',
  '--text-muted': '#5F6C7B',
  '--text-faint': '#8B97A5',
  '--accent-strong': '#1D4ED8',
  '--background-secondary': '#F4F6F8',
  '--background-modifier-border': '#D6DEE8',
  '--text-highlight-bg': 'rgba(76, 141, 255, 0.16)',
} as unknown as CSSProperties;

/** "fallback" is the deterministic stub, not analysis. The user must be able to tell. */
function GeneratorBadge({ generator }: { generator?: string | null }) {
  if (!generator) return null;
  if (generator === 'fallback') {
    return (
      <span
        className="inline-flex items-center gap-1 rounded-full border border-amber-300 bg-amber-50 px-2 py-0.5 text-[11px] font-medium text-amber-800"
        title="This text was assembled by a deterministic stub because no model ran. It is not analysis."
      >
        <AlertTriangle className="h-3 w-3" />
        Fallback stub — not model analysis
      </span>
    );
  }
  return (
    <span className="truncate text-[11px] text-gray-400" title={`Generated by ${generator}`}>
      via {generator}
    </span>
  );
}

function TopicCard({ topic }: { topic: ExpertTopic }) {
  const postCount = asArray<string>(topic.post_ids).length;
  return (
    <div className="rounded-lg border border-gray-200 bg-gray-50 p-3">
      <div className="flex flex-wrap items-baseline gap-2">
        <h4 className="text-sm font-semibold text-gray-900">{topic.title || 'Untitled topic'}</h4>
        <span className="text-xs text-gray-500">
          {postCount} {postCount === 1 ? 'post' : 'posts'}
        </span>
      </div>
      {topic.summary && (
        <div className="mt-1 text-sm text-gray-700" style={LIGHT_MARKDOWN_VARS}>
          <Suspense fallback={<p className="whitespace-pre-wrap text-gray-700">{topic.summary}</p>}>
            <MarkdownRenderer content={topic.summary} />
          </Suspense>
        </div>
      )}
    </div>
  );
}

export default function TrackBriefingPanel({
  folderId,
  className = '',
}: {
  folderId: string;
  className?: string;
}) {
  const [expert, setExpert] = useState<Expert | null>(null);
  const [briefing, setBriefing] = useState<ExpertRunResult | null>(null);
  const [history, setHistory] = useState<ExpertBriefingHistoryEntry[]>([]);
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [switching, setSwitching] = useState(false);
  const [open, setOpen] = useState(true);

  const load = useCallback(async () => {
    // No folder means no binding to look up; never leave the panel on a skeleton.
    if (!folderId) {
      setLoading(false);
      return;
    }
    setLoading(true);
    setExpert(null);
    setBriefing(null);
    // /api/experts has no folder filter; the binding is expert.folder_id.
    const res = await apiService.getExperts();
    const bound = asArray<Expert>(res?.experts).find((e) => e?.folder_id === folderId) || null;
    setExpert(bound);
    if (!bound) {
      setLoading(false);
      return;
    }
    const [result, past] = await Promise.all([
      apiService.getExpertBriefing(bound.id),
      apiService.getExpertBriefingHistory(bound.id),
    ]);
    setBriefing(result ?? null);
    const entries = asArray<ExpertBriefingHistoryEntry>(past?.briefings);
    setHistory(entries);
    setSelectedDate(entries[0]?.end_date ?? null);
    setLoading(false);
  }, [folderId]);

  /** Load one past briefing by its end date. Cached server-side; costs no LLM call. */
  const selectDate = useCallback(
    async (endDate: string) => {
      if (!expert || endDate === selectedDate) return;
      setSwitching(true);
      const result = await apiService.getExpertBriefing(expert.id, endDate);
      if (result?.success) {
        setBriefing(result);
        setSelectedDate(endDate);
      }
      setSwitching(false);
    },
    [expert, selectedDate],
  );

  useEffect(() => {
    void load();
  }, [load]);

  if (loading) {
    return (
      <div className={`animate-pulse rounded-xl border border-gray-200 bg-white p-4 ${className}`}>
        <div className="h-4 w-1/3 rounded bg-gray-200" />
        <div className="mt-3 h-3 w-2/3 rounded bg-gray-100" />
        <div className="mt-1.5 h-3 w-1/2 rounded bg-gray-100" />
      </div>
    );
  }

  // No expert bound to this folder: say so plainly and point at where to fix it.
  if (!expert) {
    return (
      <div
        className={`rounded-xl border border-dashed border-gray-300 bg-white p-4 text-sm text-gray-600 ${className}`}
      >
        <span className="font-medium text-gray-900">No expert is bound to this folder.</span> A
        folder expert writes the recurring topic briefing you would read here.{' '}
        <Link to="/experts" className="text-blue-600 hover:underline">
          Create one in Experts →
        </Link>
      </div>
    );
  }

  const hasBriefing = Boolean(briefing?.success);
  const topics = asArray<ExpertTopic>(briefing?.topics);

  if (!hasBriefing) {
    return (
      <div className={`rounded-xl border border-gray-200 bg-white p-4 ${className}`}>
        <div className="flex items-center gap-2">
          <BookOpen className="h-4 w-4 text-indigo-500" />
          <span className="text-sm font-semibold text-gray-900">{expert.name}</span>
        </div>
        <p className="mt-1 text-sm text-gray-600">
          {(briefing?.error || 'No briefing generated yet').replace(/\.\s*$/, '')}. Briefings are
          written on the Experts page or by the scheduler — opening this track generates nothing.{' '}
          <Link to="/experts" className="text-blue-600 hover:underline">
            Open Experts →
          </Link>
        </p>
      </div>
    );
  }

  /** Past runs, newest first. Each is already stored, so switching costs nothing. */
  const historyStrip =
    history.length > 1 ? (
      <div className="flex flex-wrap items-center gap-1.5 border-t border-gray-100 px-4 py-2">
        <span className="mr-1 text-[11px] uppercase tracking-wider text-gray-400">History</span>
        {history.slice(0, 14).map((entry) => {
          const date = entry.end_date || entry.subject_key;
          const isActive = date === selectedDate;
          return (
            <button
              key={entry.id}
              onClick={() => void selectDate(date as string)}
              disabled={switching}
              title={`${entry.posts_processed ?? '?'} posts · ${entry.generator ?? 'unknown generator'}`}
              className={`rounded px-1.5 py-0.5 text-[11px] transition disabled:opacity-50 ${
                isActive
                  ? 'bg-gray-900 text-white'
                  : 'border border-gray-200 bg-white text-gray-600 hover:bg-gray-50'
              }`}
            >
              {(date || '').slice(5)}
              {entry.generator === 'fallback' && <span className="ml-1 text-amber-500">!</span>}
            </button>
          );
        })}
      </div>
    ) : null;

  return (
    <section className={`rounded-xl border border-gray-200 bg-white ${className}`}>
      <div className="flex items-start gap-2 p-4">
        <button
          onClick={() => setOpen((v) => !v)}
          aria-expanded={open}
          className="flex min-w-0 flex-1 items-start gap-2 text-left"
        >
          {open ? (
            <ChevronDown className="mt-0.5 h-4 w-4 shrink-0 text-gray-400" />
          ) : (
            <ChevronRight className="mt-0.5 h-4 w-4 shrink-0 text-gray-400" />
          )}
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2">
              <BookOpen className="h-4 w-4 shrink-0 text-indigo-500" />
              <h2 className="text-base font-semibold text-gray-900">{expert.name} briefing</h2>
              <GeneratorBadge generator={briefing?.generator} />
            </div>
            <div className="mt-1 text-xs text-gray-500">
              {briefing?.posts_processed ?? 0} posts
              {briefing?.start_date && briefing?.end_date
                ? ` · ${briefing.start_date} → ${briefing.end_date}`
                : ''}
              {topics.length > 0 ? ` · ${topics.length} topics` : ''}
            </div>
          </div>
        </button>
        <button
          onClick={() => void load()}
          aria-label="Reload briefing"
          title="Reload the stored briefing (does not generate a new one)"
          className="shrink-0 rounded-md border border-gray-200 bg-white p-1.5 text-gray-500 hover:bg-gray-50"
        >
          <RefreshCw className="h-3.5 w-3.5" />
        </button>
      </div>

      {historyStrip}

      {open && (
        <div className={`border-t border-gray-100 p-4 ${switching ? 'opacity-50' : ''}`}>
          {briefing?.briefing && (
            <div className="text-sm text-gray-800" style={LIGHT_MARKDOWN_VARS}>
              <Suspense
                fallback={<p className="whitespace-pre-wrap text-gray-800">{briefing.briefing}</p>}
              >
                <MarkdownRenderer content={briefing.briefing} />
              </Suspense>
            </div>
          )}
          {topics.length > 0 && (
            <div className="mt-3 space-y-2">
              {topics.map((topic, i) => (
                <TopicCard key={`${topic.title}-${i}`} topic={topic} />
              ))}
            </div>
          )}
        </div>
      )}
    </section>
  );
}
